server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
    context-path: /dt
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql

#redis集群
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000ms
    password: 12345
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms



  datasource:
    name: li_so
    url: jdbc:mysql://47.93.52.207:3306/li_so?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin.1
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 2
    #数据库连接池的最小维持连接数
    max-idle: 2
    min-idle: 2
    #初始化提供的连接数
    initial-size: 2
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: false
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 3000
    max-wait: 3000
    jmx-enabled: true

  data:
    jpa:
      repositories:
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml

#配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log
